new playgroud

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -14,55 +14,55 @@ env:
   K8S_NAMESPACE: default  
 
 jobs:
-#   terraform:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v4
+  terraform:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
 
-#       - name: Configure AWS credentials
-#         uses: aws-actions/configure-aws-credentials@v4
-#         with:
-#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#           aws-region: ${{ env.AWS_REGION }}
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
    
-#       - name: Install jq 
-#         run: sudo apt-get update && sudo apt-get install -y jq
+      - name: Install jq 
+        run: sudo apt-get update && sudo apt-get install -y jq
       
-#       - name: Setup Terraform
-#         uses: hashicorp/setup-terraform@v3
-#         with: 
-#           terraform_wrapper: false
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with: 
+          terraform_wrapper: false
 
-#       - name: Terraform Init
-#         working-directory: ${{ env.TF_DIR }}
-#         run: terraform init -upgrade
+      - name: Terraform Init
+        working-directory: ${{ env.TF_DIR }}
+        run: terraform init -upgrade
 
-#       - name: Terraform Validate
-#         working-directory: ${{ env.TF_DIR }}
-#         run: terraform validate
+      - name: Terraform Validate
+        working-directory: ${{ env.TF_DIR }}
+        run: terraform validate
 
-#       - name: Terraform Plan
-#         id: plan
-#         working-directory: ${{ env.TF_DIR }}
-#         shell: bash
-#         run: |
-#           set +e
-#           terraform plan -input=false -detailed-exitcode -out=tfplan
-#           code=$?
-#           echo "Terraform exit code: $code"
-#           echo "exit_code=$code" >> $GITHUB_OUTPUT
-#           set -e
-#           if [ "$code" -eq 1 ]; then
-#             echo "Plan failed"; exit 1
-#           fi
+      - name: Terraform Plan
+        id: plan
+        working-directory: ${{ env.TF_DIR }}
+        shell: bash
+        run: |
+          set +e
+          terraform plan -input=false -detailed-exitcode -out=tfplan
+          code=$?
+          echo "Terraform exit code: $code"
+          echo "exit_code=$code" >> $GITHUB_OUTPUT
+          set -e
+          if [ "$code" -eq 1 ]; then
+            echo "Plan failed"; exit 1
+          fi
 
-#       - name: Terraform Apply
-#         if: ${{ github.event_name == 'push' && steps.plan.outputs.exit_code == '2' }}
-#         working-directory: ${{ env.TF_DIR }}
-#         run: terraform apply -auto-approve tfplan
+      - name: Terraform Apply
+        if: ${{ github.event_name == 'push' && steps.plan.outputs.exit_code == '2' }}
+        working-directory: ${{ env.TF_DIR }}
+        run: terraform apply -auto-approve tfplan
 
 #   build-and-push:
 #     if: github.event_name == 'push'
