playground

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -89,13 +89,12 @@ jobs:
         run: |
           ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
           REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/fastapi-app
-          IMAGE_TAG=latest
+          IMAGE_TAG="${GITHUB_SHA}"
 
           docker build -t $REPOSITORY_URI:$IMAGE_TAG .
 
           docker push $REPOSITORY_URI:$IMAGE_TAG
-
-          aws eks update-kubeconfig --region $AWS_REGION --name cluster1
+          echo "image_uri=$REPOSITORY_URI:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
 
   deploy:
     if: github.event_name == 'push'
@@ -125,11 +124,26 @@ jobs:
         working-directory: ${{ env.TF_DIR }}
         run: terraform init 
 
+      - name: Terraform Plan (k8s)
+        id: k8s_plan
+        working-directory: ${{ env.TF_DIR }}
+        shell: bash
+        run: |
+          set +e
+          terraform plan \
+            -var="docker_image_uri=${{ needs.build-and-push.outputs.image_uri }}" \
+            -var="k8s_namespace=${{ env.K8S_NAMESPACE }}" \
+            -input=false -detailed-exitcode -out=tfplan
+          code=$?
+          echo "exit_code=$code" >> $GITHUB_OUTPUT
+          set -e
+          if [ "$code" -eq 1 ]; then echo "Plan failed"; exit 1; fi
       - name: Apply Kubernetes Deployment via Terraform
         working-directory: ${{ env.TF_DIR }}
         run: |
-          terraform apply -auto-approve -var="docker_image_uri=${{ needs.build-and-push.outputs.image_uri }}"
-          
+          terraform apply -auto-approve \
+          -var="docker_image_uri=${{ needs.build-and-push.outputs.image_uri }}" \
+          -var="k8s_namespace=${{ env.K8S_NAMESPACE }}"        
   # deploy-to-s3:
   #   runs-on: ubuntu-latest
   #   needs: terraform
