changes in ci/cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -44,18 +44,21 @@ jobs:
         shell: bash
         run: |
           set +e
-          terraform plan -detailed-exitcode -out=tfplan
-          code=$?
-          echo "exit_code=$code"
-          echo "exit_code=$code" >> $GITHUB_ENV
-          if [ $code -eq 1 ]; then
-            echo "Plan failed"; exit 1
+          terraform plan -detailed-exitcode -input=false -out=tfplan
+          exit_code=$?
+          set -e
+          if [ $exit_code -eq 2 ]; then
+            echo "There are pending changes."
+            exit 0
+          elif [ $exit_code -eq 0 ]; then
+            echo "No changes detected in the Terraform plan."
+            exit 0
+          else
+            echo "Terraform plan failed."
+            exit 1
           fi
 
 
-      - name: No changes — skip apply
-        if: github.event_name == 'push' && env.exit_code == '0'
-        run: echo "No changes detected. Skipping apply."
       - name: Terraform Apply (only when changes exist)
         if: github.event_name == 'push' && env.exit_code == '2'
         working-directory: ${{ env.TF_DIR }}
